---
host_firewall_enabled: true
host_firewall_internal_network: 10.15.0.0/16
host_firewall_ssh_sources:
  - 10.15.0.0/16
  - 100.64.0.0/10
host_firewall_common_rules: []

tailscale_authkey: "{{ lookup('community.general.onepassword', 'tailscale-authkey', vault='Homelab', field='credential') }}"
beszel_hub_url: "http://10.15.1.13:8090"
