[proxmox]
pve ansible_host=10.15.1.10 ansible_user=root ansible_python_interpreter=/usr/bin/python3

[dns_primary]
dns01 ansible_host=10.15.1.11 ansible_user=root ansible_python_interpreter=/usr/bin/python3

[dns_secondary]
dns02 ansible_host=10.15.1.12 ansible_user=cbrand ansible_python_interpreter=/usr/bin/python3

[dns:children]
dns_primary
dns_secondary

[monitoring_hosts]
monitoring ansible_host=10.15.30.52 ansible_user=root ansible_python_interpreter=/usr/bin/python3

[beszel_hubs]
beszel ansible_host=10.15.1.13 ansible_user=root ansible_python_interpreter=/usr/bin/python3

[tautulli_servers]
tautulli ansible_host=10.15.30.18 ansible_user=root ansible_python_interpreter=/usr/bin/python3

[sonarr_servers]
sonarr01 ansible_host=10.15.30.12 ansible_user=root ansible_python_interpreter=/usr/bin/python3
sonarr02 ansible_host=10.15.30.13 ansible_user=root ansible_python_interpreter=/usr/bin/python3

[prowlarr_servers]
prowlarr ansible_host=10.15.30.14 ansible_user=root ansible_python_interpreter=/usr/bin/python3

[notifiarr_clients]
notifiarr ansible_host=10.15.30.15 ansible_user=root ansible_python_interpreter=/usr/bin/python3

[seerr_servers]
seerr ansible_host=10.15.30.16 ansible_user=root ansible_python_interpreter=/usr/bin/python3

[radarr_servers]
radarr01 ansible_host=10.15.30.10 ansible_user=root ansible_python_interpreter=/usr/bin/python3
radarr02 ansible_host=10.15.30.11 ansible_user=root ansible_python_interpreter=/usr/bin/python3

[arr]
radarr01
radarr02
sonarr01
sonarr02
prowlarr

[media]
notifiarr
seerr
tautulli

[sabnzbd_servers]
sabnzbd ansible_host=10.15.30.17 ansible_user=root ansible_python_interpreter=/usr/bin/python3

[qbittorrent_servers]
qbittorrent ansible_host=10.15.30.19 ansible_user=root ansible_python_interpreter=/usr/bin/python3

[downloaders:children]
sabnzbd_servers
qbittorrent_servers

[media_servers]
plex ansible_host=10.15.30.7 ansible_user=root ansible_python_interpreter=/usr/bin/python3

[media:children]
arr
downloaders
media_servers

[backup_services]
radarr01
radarr02
sonarr01
sonarr02
prowlarr
notifiarr
seerr
sabnzbd
qbittorrent
tautulli
plex

[lxcs:children]
dns_primary
beszel_hubs
monitoring_hosts
media

[single_board_computers:children]
dns_secondary

[beszel_agents:children]
proxmox
lxcs
single_board_computers

[beszel_agent_excluded]
beszel
