---
- name: update apt cache
  apt:
    update_cache: yes
  become: true

- name: install prerequisites
  apt:
    name:
      - dnsutils
      - gzip
      - tar
    state: present
  become: true

- name: Download Technitium DNS installer
  ansible.builtin.get_url:
    url: https://download.technitium.com/dns/install.sh
    dest: /tmp/technitium-dns-install.sh
    mode: "0755"

- name: Run Technitium DNS installer
  ansible.builtin.command:
    argv:
      - /bin/bash
      - /tmp/technitium-dns-install.sh
  args:
    creates: /etc/dns
  become: true

- name: ensure technitium dns service is running
  systemd:
    name: dns
    state: started
    enabled: yes
  become: true
